export const actionType = {
    orderAdd:'orderAdd',
    orderEdit:'orderEdit',
    orderDelete:'orderDelete',
    orderUpdate:'orderUpdate',
    cartAdd:'cartAdd',
    cartEdit:'cartEdit',
    cartDelete:'cartDelete',
    cartUpdate:'cartUpdate',
    usersAdd:'usersAdd',
    usersEdit:'usersEdit',
    usersDelete:'usersDelete',
    usersUpdate:'usersUpdate',
    orderItemAdd:'orderItemAdd',
    orderItemUpdate:'orderItemUpdate',
    profileAdd:'profileAdd',
    profileEdit:'profileEdit',
    profileDelete:'profileDelete',
    profileUpdate:'profileUpdate',
    carsAdd:'carsAdd',
    carsEdit:'carsEdit',
    carsDelete:'carsDelete',
    carsUpdate:'carsUpdate',
    productAdd:'productAdd',
    productEdit:'productEdit',
    productDelete:'productDelete',
    productUpdate:'productUpdate',
    menu:'menu',
    // admin login
    user:'user',
    logout:'logout',
    load:'load',
    date:'date'

}